### PR TITLE
Differentiate unsupported project messages

### PR DESCRIPTION
**Pull request by Lawrencemm**
Give separate messages for missing conan and missing conanfile.

### CODE REVIEW

**Comment by eyalbe4** [comment]
Thanks for pull request @Lawrencemm!
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by Lawrencemm** [comment]
Ok, cla signed.

**Comment by Lawrencemm** [comment]
Is there another step for the CLA? Do I need to link it to Github or something?

**Comment by jgsogo** [comment]
Hi! Would you mind to rebase your PR on top of `dev` branch and change the PR to target `dev`? 

Thanks!

**Comment by jgsogo** [comment]
For the CI to pass I need to get PR https://github.com/conan-io/conan-clion-plugin/pull/41 merged first, but we are on our way 😉 

Thanks for taking care of this PR.

**Pull request merged**
